# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('stadion', models.CharField(max_length=30)),
                ('miasto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Druzyna_Zawodnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_druzyny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Druzyna')),
            ],
        ),
        migrations.CreateModel(
            name='Klasyfikacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecze', models.IntegerField(default=0)),
                ('zwyciestwa', models.IntegerField(default=0)),
                ('remisy', models.IntegerField(default=0)),
                ('porazki', models.IntegerField(default=0)),
                ('bramki_stracone', models.IntegerField(default=0)),
                ('bramki_strzelone', models.IntegerField(default=0)),
                ('punkty', models.IntegerField(default=0)),
                ('id_druzyny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Druzyna')),
            ],
        ),
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('bramki_1', models.IntegerField(default=0)),
                ('bramki_2', models.IntegerField(default=0)),
                ('nr_kolejki', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mecz_Druzyna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_druzyny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Druzyna')),
                ('id_meczu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Mecz')),
            ],
        ),
        migrations.CreateModel(
            name='Statystyka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bramki', models.IntegerField(default=0)),
                ('asysty', models.IntegerField(default=0)),
                ('kartka_czerwona', models.IntegerField(default=0)),
                ('kartka_zolta', models.IntegerField(default=0)),
                ('id_meczu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Mecz')),
            ],
        ),
        migrations.CreateModel(
            name='Strzelec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bramki', models.IntegerField(default=0)),
                ('asysty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('pozycja', models.CharField(max_length=10)),
                ('data_urodzenia', models.DateField()),
                ('narodowosc', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='strzelec',
            name='id_zawodnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Zawodnik'),
        ),
        migrations.AddField(
            model_name='statystyka',
            name='id_zawodnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Zawodnik'),
        ),
        migrations.AddField(
            model_name='druzyna_zawodnik',
            name='id_zawodnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Zawodnik'),
        ),
    ]
